#!/bin/sh

# VasútTérkép container entrypoint (Dockerfile CMD), run from /app.
#
# /app/server.js is Next.js's STANDALONE server, generated by `next build`
# (output: 'standalone') and copied from .next/standalone by the Dockerfile.
# There is no custom server in the repo. The background worker
# (dist/worker/index.js, compiled by `tsc --project tsconfig.worker.json`)
# fetches MÁV data into Redis; the web server only reads from Redis.
echo "🚀 Starting VasútTérkép application..."

# Check if required files exist
if [ ! -f "server.js" ]; then
    echo "❌ server.js (Next.js standalone server) not found!"
    exit 1
fi

if [ ! -f "dist/worker/index.js" ]; then
    echo "⚠️  Worker not found, starting web server only..."
    exec node server.js
fi

# Stop both children
stop_children() {
    if [ ! -z "$WORKER_PID" ]; then
        kill $WORKER_PID 2>/dev/null
    fi
    if [ ! -z "$WEB_PID" ]; then
        kill $WEB_PID 2>/dev/null
    fi
}

# Graceful shutdown on SIGTERM/SIGINT (docker stop, redeploy)
cleanup() {
    echo "🛑 Shutting down application..."
    stop_children
    exit 0
}

# Set up signal traps
trap cleanup SIGTERM SIGINT

echo "🔧 Starting background worker..."
node dist/worker/index.js &
WORKER_PID=$!
echo "✅ Worker started (PID: $WORKER_PID)"

echo "🌐 Starting web server..."
node server.js &
WEB_PID=$!
echo "✅ Web server started (PID: $WEB_PID)"

echo "🎉 VasútTérkép is running!"
echo "   Web: http://localhost:${PORT:-3000}"
echo "   Health: http://localhost:${PORT:-3000}/api/health"

# Wait for any process to exit
wait -n
exit_code=$?

# One of the two died: take the other down too and exit with the child's code,
# so the container stops (and gets restarted) instead of limping on half-alive.
echo "💥 Process exited with code: $exit_code"
stop_children
exit $exit_code
